project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - pages/qmc-software.qmd
  resources:
    - assets/**
    - classlib/classlib/quarto/**
    - classlib/classlib/notebooks/**

format:
  html:
    css:
      - classlib/classlib/quarto/website/hickernell-website.css
    include-in-header:
      - classlib/classlib/quarto/slides/hickernell-latex-macros.js
    link-external-newwindow: true

metadata-files:
  - classlib/classlib/quarto/website/hickernell-website.yml
  - classlib/classlib/quarto/metadata/hickernell-texts.yml

website:
  title: "MCQMC 2026"
  navbar:
    logo: classlib/classlib/quarto/assets/images/normal-scatter.png
    left:
      - href: index.qmd
        text: Home
      - href: slides/Plenary_MCQMC2026.html
        text: Plenary talk slides
      - href: slides/SpecialSession_MCQMC2026.html
        text: Special session talk slides
      - href: pages/qmc-software.html
        text: QMC Software


    right:
      - text: Related
        menu:
          - text: Talk Repository
            icon: github
            href: https://github.com/fjhickernell/MCQMC26
          - text: QMCPy
            href: https://qmcpy.org

  page-footer:
    left: "© 2026 Fred J. Hickernell · Illinois Institute of Technology · assisted by ChatGPT"

course_repo: "https://github.com/fjhickernell/MCQMC26"
course_repo_label: "MCQMC26 on GitHub"

execute:
  warning: false
  message: false

