---
title: "17th International Conference on Monte Carlo and Quasi-Monte Carlo Methods in Scientific Computing (MCQMC 2026)"
metadata-files:
  - classlib/classlib/quarto/website/hickernell-website.yml
title-block-banner: false
---

### Edinburgh, UK, June 8–12, 2026

### Fred J. Hickernell
Illinois Institute of Technology <br>
[hickernell@illinoistech.edu](mailto:hickernell@illinoistech.edu)

## Plenary Talk

### Where Quasi-Monte Carlo <br>Theory and Practice Meet

Quasi-Monte Carlo (QMC) methods are underpinned by deep mathematical theory and have demonstrated high-impact computational performance. A wide range of low-discrepancy sequences and QMC algorithms have been developed and implemented in modern software libraries.

Despite this progress, key challenges remain: selecting effective sequences for real problems, formulating computations to fully exploit QMC structure, and developing reliable, data-driven error assessment.

This talk examines these challenges through the lens of both theory and practice, offering perspectives on how the two can be more tightly integrated and where future advances may emerge.

[Slides](slides/MCQMC2026_Plenary.html)

## Special Session Talk

### Good Lattice and Kronecker Sequences for Arbitrary Sample Sizes

Low discrepancy sequences used for quasi-Monte Carlo computations are often optimized for a sequence of sample sizes, such as powers of a prime base. This is particularly true for lattices and digital sequences. While the preferred sample sizes are best, the user might not be able to fully control the node set because of budget constraints or missing data. We explore how well one can do for arbitrary sample sizes, in particular for lattices and Kronecker sequences. We derive a weighted sum of squared expected discrepancies over all sample sizes as our figure of merit. We use component-by-component constructions to obtain new low discrepancy sequences.

[Slides](slides/MCQMC2026_SpecialSession.html)



## Conference

- [MCQMC 2026 website](https://mcqmc2026.org/)
- [June, 2026 Special Session in program](https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=86001)



## Repository

- [MCQMC26 on GitHub](https://github.com/fjhickernell/MCQMC26)
- [QMCPy](https://qmcpy.org)